# Generated by Django 3.1.7 on 2023-10-30 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20231029_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='postal_zip_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state_province_region',
        ),
    ]
