# Generated by Django 3.1.7 on 2023-10-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20231004_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='compare_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
